def antsmarch(number,little):
    print("The ants go marching",number,"by",number,"hurrah! hurrah!")
    print("The ants go marching",number,"by",number,"hurrah! hurrah!")
    print("The ants go marching on by",number+",")
    print("The little one stops to",little+",")
    print("And they all go marching down...")
    print("In the ground...")
    print("To get out...")
    print("Of the rain.")
    print("Boom! Boom! Boom!")
    
def antssong():
    antsmarch(number="one",little="suck his thumb")
    print (" ")
    antsmarch(number="two",little="tie his shoe")
    print (" ")
    antsmarch(number="three",little="vape")
    print (" ")
    antsmarch(number="four",little="climb a tree")
    print (" ")
    antsmarch(number="five",little="eat a pear")
    print (" ")
    antsmarch(number="six",little="twirl around")
    print (" ")
    antsmarch(number="seven",little="get backpain")
    print (" ")
    antsmarch(number="eight",little="fall down")
    print (" ")
    antsmarch(number="nine",little="do the chacha slide")
    print (" ")
    antsmarch(number="ten",little="take a nap")
    print (" ")
antssong()
    