def about_you():
    print ("Welcome to 'My About You' Challenge")
    n = input ("Hello, what is your name? " )
    print ("Hello "+n+",very nice to meet you!")
    c = input ("What is your favorite color? ") 
    print ("I love "+c+" so much!")    
    a = int(input ("How old are you? "))
    print ("You are",a,"years old.")
    w = input ("What is your favorite day of the week? ")
    print ("I think "+w+" can be a bit boring.")
    z = input ("Do you like cats or dogs? ")
    print ("I like "+z+" too!")
    print ("Ok, I think I got this down. I'm gonna tell you a story about yourself!")
    q = input ("Do you want to hear it (y/n)? ")
    print ("Your name is "+n+" and your favorite color is "+c+".You are ",a," years old and your favorite day of the week is "+w+" which is a pretty boring day.""You like "+z+" which are my favorite pets!")
about_you()